- name: "Create POP {{ policy_pop_name }}"
  ibm.isam.isamadmin:
    log: "{{ log_level | default('INFO') }}"
    isamuser: "{{ execute_pdadmin_isamuser }}"
    isampwd: "{{ execute_pdadmin_isampwd }}"
    ignore_error: True
    commands:
    - "pop create {{ policy_pop_name }}"
  register: create_policy_pop_result
  failed_when: create_policy_pop_result.rc != 500 and not create_policy_pop_result.rc == 0 and not create_policy_pop_result.data.result is search('A protected object policy with this name already exists')
  changed_when: create_policy_pop_result.rc == 0


- name: "Set description on POP {{ policy_pop_name }}"
  ibm.isam.isamadmin:
    log: "{{ log_level | default('INFO') }}"
    isamuser: "{{ execute_pdadmin_isamuser }}"
    isampwd: "{{ execute_pdadmin_isampwd }}"
    ignore_error: True
    commands:
    - "pop modify {{ policy_pop_name }} set description \"{{ policy_pop_description }}\""
  register: description_policy_pop_result
  failed_when: description_policy_pop_result.rc != 0
  changed_when: description_policy_pop_result.rc == 0
  when: create_policy_pop_result.changed and policy_pop_description is defined

- name: "Set config items on POP {{ policy_pop_name }}"
  ibm.isam.isamadmin:
    log: "{{ log_level | default('INFO') }}"
    isamuser: "{{ execute_pdadmin_isamuser }}"
    isampwd: "{{ execute_pdadmin_isampwd }}"
    ignore_error: True
    commands:
    - "pop modify {{ policy_pop_name }} set {{ item.key }} {{ item.value }}"
  register: config_policy_pop_result
  failed_when: config_policy_pop_result.rc != 0
  when: create_policy_pop_result.changed and policy_pop_config is defined and policy_pop_config | length > 0
  loop: "{{ policy_pop_config | dict2items}}"

- name: "Set attribute on POP {{ policy_pop_name }}"
  ibm.isam.isamadmin:
    log: "{{ log_level | default('INFO') }}"
    isamuser: "{{ execute_pdadmin_isamuser }}"
    isampwd: "{{ execute_pdadmin_isampwd }}"
    ignore_error: True
    commands:
    - "pop modify {{ policy_pop_name }} set attribute {{ item.0.attr_name }} {{ item.1 }}"
  register: attribute_policy_pop_result
  failed_when: attribute_policy_pop_result.rc != 0
  when: create_policy_pop_result.changed and policy_pop_attributes is defined and policy_pop_attributes | length > 0
  loop: "{{ policy_pop_attributes | subelements('attr_value')}}"
  loop_control:
    label: "{{ item.0.attr_name }} - {{ item.1 }}"
