- name: Delete reverse proxy config entry
  ibm.isam.isam:
    log: "{{ log_level | default('INFO') }}"
    force: "{{ force | default(False) }}"
    action: ibmsecurity.isam.web.reverse_proxy.configuration.entry.delete
    isamapi:
      reverseproxy_id: "{{ reverseproxy_conf_reverseproxy_id }}"
      stanza_id: "{{ item.0.stanza_id }}"
      entry_id: "{{ item.1.0 }}"
      value_id: "{{ item.1.1 | default(None) }}"
  loop: "{{ reverseproxy_conf_entries | subelements('entries') }}"
  loop_control:
    label: "\nstanza: [{{ item.0.stanza_id }}] \n\tentry:\n\t{{ item.1.0 }} = {{ item.1.1 | default(None)}}"
  notify:
  - Commit Changes
  - Restart Reverse Proxy
