galaxy_info:
  author: zone-zero
  description: Idempotent role to add/remove transformation rule
  company: VF

  license: Apache

  min_ansible_version: 2.5
  platforms:
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
  - isam
  - ibm
  - httptransformation
  - import

dependencies:
  - common_handlers
